### GET
GET http://localhost:8085/venta/1


### POST
POST http://localhost:8085/venta
Content-Type: application/json

{
  "automotorId": 1,
  "clienteId": 1,
  "empleadoId": 2,
  "sucursalId": 1
}


###AUTOMOTOR
### GET
GET http://localhost:8084/automotor/1


### POST
POST http://localhost:8084/automotor
Content-Type: application/json

{
  "modelo": "A3",
  "marca": "Audi",
  "anio": 2015,
  "precioBase": 1000,
  "aniosGarantia": 3
}

###INVENTARIO LOCAL
### GET
GET http://localhost:8080/inventario-local/stock?sucursalId=1&automotorId=1

### POST
POST http://localhost:8080/inventario-local
Content-Type: application/json

{
  "sucursalId": 1,
  "automotorId": 1,
  "cantidad": 3,
  "tiempoEntrega": 2
}

###INVENTARIO CENTRAL
### GET
GET http://localhost:8080/inventario-central/stock?automotorId=4

### POST
POST http://localhost:8080/inventario-central
Content-Type: application/json

{
  "automotorId": 4,
  "cantidad": 3,
  "tiempoEntrega": 2
}


###SUCURSAL
### GET
GET http://localhost:8081/sucursal/1


### POST
POST http://localhost:8081/sucursal
Content-Type: application/json

{
  "nombre": "SucursalTITO",
  "direccion": "San Isidro",
  "pais": "Argentina",
  "fechaApertura": "2020-01-08"
}


###CLIENTE
### GET
GET http://localhost:8083/cliente/1


### POST
POST http://localhost:8083/cliente
Content-Type: application/json

{
  "nombre": "Adolin",
  "email": "adolin@gmail.com",
  "direccion": "Kholinar",
  "dni": "1234567",
  "telefono": "443322211"
}

###EMPLEADO
### GET
GET http://localhost:8083/empleado/2

### POST
POST http://localhost:8083/empleado
Content-Type: application/json

{
  "nombre": "Dalinar",
  "email": "dalinar@gmail.com",
  "direccion": "Kholinar",
  "dni": "1234567",
  "puesto": "Vendedor",
  "concessionId": 1
}