### GET
GET http://localhost:8083/cliente/2


### POST
POST http://localhost:8083/cliente
Content-Type: application/json

{
  "nombre": "Adolin",
  "email": "adolin@gmail.com",
  "direccion": "Kholinar",
  "dni": "1234567",
  "telefono": "443322211"
}