### GET
GET http://localhost:8082/taller/1


### POST
POST http://localhost:8082/taller
Content-Type: application/json

{
  "automotorId": 1,
  "sucursalId": 1,
  "clienteId": 1,
  "fechaRecepcion": "2025-06-18",
  "descripcion": "Cambio de aceite",
  "kilometros": 2500
}